# Generated by Django 5.1.3 on 2024-11-17 16:34

import django.db.models.deletion
import mal_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('mean', models.FloatField()),
                ('media_type', models.CharField(max_length=20)),
                ('num_episodes', models.IntegerField()),
                ('average_episode_duration', models.FloatField()),
                ('studio', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('joined_at', models.DateField()),
                ('picture', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Anime_Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mal_api.anime')),
                ('genre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mal_api.genre')),
            ],
        ),
        migrations.CreateModel(
            name='User_Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(validators=[mal_api.models.validate_score])),
                ('status', models.CharField(choices=[('completed', 'completed'), ('watching', 'watching'), ('on_hold', 'on_hold'), ('dropped', 'dropped'), ('plan_to_watch', 'plan_to_watch')], max_length=20)),
                ('num_watched_episodes', models.IntegerField()),
                ('start_date', models.DateField(null=True)),
                ('finish_date', models.DateField(null=True)),
                ('anime_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mal_api.anime')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mal_api.user')),
            ],
        ),
    ]
