# Generated by Django 5.1.3 on 2024-11-17 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mal_api', '0002_user_access_token_user_last_login_user_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=True),
        ),
    ]
