# Generated by Django 5.1.3 on 2024-11-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mal_api', '0003_user_is_staff_user_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='studio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
