# Generated by Django 5.1.3 on 2024-11-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mal_api', '0004_alter_anime_studio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
