# Generated by Django 5.1.3 on 2024-11-18 18:30

import mal_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mal_api', '0005_alter_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_anime',
            name='num_watched_episodes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user_anime',
            name='score',
            field=models.FloatField(blank=True, null=True, validators=[mal_api.models.validate_score]),
        ),
    ]
