# Generated by Django 5.1.3 on 2024-11-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mal_api', '0006_alter_user_anime_num_watched_episodes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='mean',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
