# Generated by Django 5.1.3 on 2024-11-22 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mal_api', '0007_alter_anime_mean'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime_genre',
            old_name='anime_id',
            new_name='anime',
        ),
        migrations.RenameField(
            model_name='anime_genre',
            old_name='genre_id',
            new_name='genre',
        ),
    ]
