# Generated by Django 5.1.3 on 2024-11-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mal_api', '0008_rename_anime_id_anime_genre_anime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_anime',
            name='finish_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_anime',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
