# Generated by Django 5.1.3 on 2024-11-26 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mal_api', '0009_alter_user_anime_finish_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_anime',
            old_name='num_watched_episodes',
            new_name='num_episodes_watched',
        ),
    ]
