# Generated by Django 5.1.3 on 2025-02-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mal_api', '0011_animelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
